name: Build and Push Container Image

on:
  workflow_call:
    inputs:
      tags:
        description: 'Tag to use for the image'
        type: string
        required: true
        default: 'dev'

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      BUILDX_NO_DEFAULT_ATTESTATIONS: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache Nuitka cache
      uses: actions/cache@v4
      with:
        path: nuitka-cache
        key: nuitka-cache

    - name: Inject Nuitka cache into Docker
      uses: reproducible-containers/buildkit-cache-dance@v2.1.4
      with:
        cache-source: nuitka-cache
        cache-target: /root/.cache/Nuitka

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        provenance: false
        tags: ${{ inputs.tags }}
        platforms: |
          linux/amd64
          linux/arm64
    
    - name: Delete all containers from package without tags
      uses: Chizkiyahu/delete-untagged-ghcr-action@v3
      with:
          token: ${{ github.token }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          package_name: subconv
          untagged_only: true
          owner_type: org
          except_untagged_multiplatform: true
